# Generated by Django 4.2 on 2023-04-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_vacancy_description_vacancy_user_survey_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='user',
            new_name='vacancy',
        ),
    ]
