# Generated by Django 4.2 on 2023-04-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_rename_user_skill_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.CharField(default='', max_length=100),
        ),
    ]
