# Generated by Django 4.2 on 2023-04-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0005_remove_survey_test_vacancy_company_skillresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(default='Зверебург', max_length=250),
        ),
    ]
