# Generated by Django 4.2 on 2023-04-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0008_rename_name_vacancy_employeer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
