# Generated by Django 4.2 on 2023-04-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='mentor_spec',
            field=models.CharField(default='', max_length=100),
        ),
    ]
