# Generated by Django 4.2 on 2023-04-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_notification_is_read_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='second_user_id',
            field=models.IntegerField(default=1),
        ),
    ]
