# Generated by Django 4.2 on 2023-04-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_question_id_alter_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
