# Generated by Django 4.2 on 2023-04-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
