# Generated by Django 4.2 on 2023-04-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_question_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='false1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='false2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='false3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='true1',
            field=models.CharField(max_length=100),
        ),
    ]
