# Generated by Django 4.2 on 2023-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_question_false1_alter_question_false2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='test',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
