# Generated by Django 4.2 on 2023-04-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_test_description_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='difficulty',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('test_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tests.test')),
                ('difficulty', models.CharField(choices=[('Легкая', 'Легкая'), ('Средняя', 'Средняя'), ('Сложная', 'Сложная')], max_length=15)),
            ],
            bases=('tests.test',),
        ),
    ]
