# Generated by Django 4.2 on 2023-04-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_question_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='random',
            field=models.BooleanField(default=False),
        ),
    ]
